### ISSUE TITLE
Peer To Peer Code Review

### ISSUE THREAD

**Issue by kubilaycaglayan** [frankopkusianwar/weather-app#2]
Hello Frank :wave: 
Thanks for your presentation :pray: 

In your fetch request function: :arrow_down: 

```
const getData = (city, celfaren) => fetch(`https://api.openweathermap.org/data/2.5/weather?q=${city}&units=${celfaren}&appid=92991e52ab85aab6dc928ff69d5ed09b`)
  .then((response) => {
    const data = response.json();
    return data;
  });
```

:bulb:  Creating another variable name for your URL would be more pretty

```
const URL = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=${celfaren}&appid=92991e52ab85aab6dc928ff69d5ed09b`
const getData = (city, celfaren) => fetch(URL)
  .then((response) => {
    const data = response.json();
    return data;
  });
```

:bulb:  And yes, in arrow functions if we are returning only one line, all in all, we can skip the curly braces and return statement but in this case we have a few lines going on, **I would prefer to wrap it in curly braces** like this:

```
const getData = (city, celfaren) => {
  const URL = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=${celfaren}&appid=92991e52ab85aab6dc928ff69d5ed09b`
  fetch(URL)
    .then((response) => {
      const data = response.json();
      return data;
  })
};
```

:bulb:  Also check the correct spelling of **Fahrenheit** please :blush: 

With all my respect...

**Comment by mariosknl** [comment]
Great project Frank. It's good that you have separated your code in different files.

**Comment by frankopkusianwar** [comment]
Thanks for the suggestions, let me work on this
